spring:
  application:
    name: persistence
  datasource:
    url: jdbc:postgresql://192.168.1.48:5432/ctdsys
    username: ctdsys_user
    password: c4t4l0g0d1g1t4l2024$
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: catalogoproveedores@itp.gob.pe
    password: wajhidteefkjdzgk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    catalogo.persistence: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

password:
  generator: itp2024$

variables:
  correo: catalogoproveedores@itp.gob.pe

users:
  creation: 20131369477
server:
  address: 11.38.80.21
  port: 9000
